income:
  categories:
    - Job:
      - pattern1
      - pattern2
    - Tips:
      - pattern1
      - pattern2
expenses:
  savings_deduction_pattern: "Transfer.*From.*Savings"
  categories:
    Food:
      - uber.*eats
      - starbucks
    Transport:
      - uber
      - shell
      - sonoco